apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  appusers.json: |-
    {
      "AppUsers" : [{
        "Id": "user",
        "Password": "usrpass",
        "FirstName": "Application",
        "LastName": "User"
      },{
        "Id": "admin",
        "Password": "admpass",
        "FirstName": "System",
        "LastName": "Administrator"
      }]
    }