apiVersion: v1
kind: Pod
spec:
    containers:
      - name: jnlp
        image: 'jenkinsci/jnlp-slave:alpine'
      - name: helm
        image: 'saharshsingh/helm:2.13.1'
        imagePullPolicy: IfNotPresent
        command:
          - /bin/cat
        tty: true
      - name: openshift-client
        image: 'openshift/origin-cli:v3.11.0'
        imagePullPolicy: IfNotPresent
        command:
          - /bin/cat
        tty: true